"""Write the M5 deep-model configs into this folder.

    python Code/configs/m5/make_configs.py

Groups (file-name prefix):
  e_  WESAD, all signals: per-subject normalisation that a device could
      actually compute ("none", first 5 minutes of wear, first 5 minutes of
      rest), against M3's whole-recording normalisation. The rest-normalised
      binary and four-class runs also carry per-user calibration.
  g_  WESAD, wrist signals only, rest normalisation, with calibration.
  h_  Stress-Predict, leave-one-subject-out over its 34 participants, binary,
      with and without the hyperventilation task, with calibration.
  i_  Cross-dataset: train on WESAD wrist data, test on every Stress-Predict
      participant. Training configs live in cross_train/.

The classical-baseline configs in this folder are written by hand.
Model architectures and the training recipe are the same as in M3.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "m3"))
from make_configs import MODELS, toml_value  # noqa: E402  (same six models as M3)

WRIST = ["wr_bvp", "wr_eda", "wr_temp", "wr_acc_x", "wr_acc_y", "wr_acc_z"]
MAIN_MODELS = ("bigru_attn", "cnn", "tiny_dscnn")  # proposed, best in M3, smallest
TASKS = ("binary", "three_class", "four_class")
CALIBRATION = [1, 2, 4]
NORMALISATION = {  # tag -> preprocess settings
    "none": {"subject_normalisation": False},
    "first5": {"normalisation_source": "first_minutes", "normalisation_minutes": 5.0},
    "rest5": {"normalisation_source": "rest_minutes", "normalisation_minutes": 5.0},
}


def write(path: Path, name: str, comment: str, task: str, model: dict, *, norm: str, dataset: str = "wesad",
          channels: list[str] | None = None, exclude_hv: bool = False, calibration: list[int] | None = None,
          out_dir: str | None = None) -> None:
    tags = [norm] + (["wrist"] if channels else []) + (["nohv"] if exclude_hv else [])
    prefix = "data_sp" if dataset == "stress_predict" else "data_clean"
    data_dir = f"{prefix}_w60_s10_r32_{'_'.join(tags)}"
    model = {"rnn_hidden": 128, "rnn_layers": 2, "attn_heads": 4, "dropout": 0.3, **model}
    pre = {
        "mode": "clean", "dataset": dataset, "target_rate": 32, "window_sec": 60, "stride_sec": 10,
        "min_label_purity": 1.0, "subject_normalisation": True, **NORMALISATION[norm],
    }
    if channels:
        pre["channels"] = channels
    if exclude_hv:
        pre["exclude_hyperventilation"] = True

    lines = [
        f"# {comment}",
        "# Generated by make_configs.py; edit that script, not this file.",
        "",
        "[run]", f'name = "{name}"', "seed = 42", "",
        "[paths]  # relative to Code/",
        f'raw_dir = "{"Stress-Predict" if dataset == "stress_predict" else "WESAD"}"',
        f'data_dir = "{data_dir}"',
        f'out_dir = "{out_dir or f"runs/m5/{name}"}"', "",
        "[preprocess]", *[f"{k} = {toml_value(v)}" for k, v in pre.items()], "",
        "[model]", 'arch = "seq"', *[f"{k} = {toml_value(v)}" for k, v in model.items()], "",
        "[train]", f'task = "{task}"', 'balancing = "weighted_sampler"', "batch_size = 128", "epochs = 40",
        "lr = 1e-3", 'lr_scheduler = "plateau"', "patience = 8", "grad_clip = 5.0",
        'validation = "subjects"', "val_subjects = 2", "val_fraction = 0.1",
    ]
    if calibration:
        lines += [f"calibration_minutes = {toml_value(calibration)}", "calibration_epochs = 10",
                  "calibration_lr = 1e-3", 'calibration_layers = "head"']
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    (HERE / "cross_train").mkdir(exist_ok=True)
    for old in list(HERE.glob("[eghi]_*.toml")) + list((HERE / "cross_train").glob("*.toml")):
        old.unlink()

    for task in TASKS:
        for model_name in MAIN_MODELS:
            for norm in NORMALISATION:
                calib = CALIBRATION if norm == "rest5" and task != "three_class" else None
                name = f"e_{task}_{model_name}_{norm}_w60"
                write(HERE / f"{name}.toml", name, f"WESAD, {model_name}, {task}, normalisation: {norm}.",
                      task, MODELS[model_name], norm=norm, calibration=calib)

            name = f"g_{task}_{model_name}_wrist_rest5_w60"
            write(HERE / f"{name}.toml", name, f"WESAD wrist only, {model_name}, {task}, rest normalisation.",
                  task, MODELS[model_name], norm="rest5", channels=WRIST,
                  calibration=CALIBRATION if task != "three_class" else None)

    for model_name, model in MODELS.items():
        for exclude_hv in (False, True):
            hv = "nohv" if exclude_hv else "hv"
            name = f"h_binary_{model_name}_{hv}_w60"
            write(HERE / f"{name}.toml", name,
                  f"Stress-Predict LOSO, {model_name}, binary, hyperventilation {'excluded' if exclude_hv else 'as stress'}.",
                  "binary", model, norm="rest5", dataset="stress_predict", channels=WRIST,
                  exclude_hv=exclude_hv, calibration=CALIBRATION)

        train_name = f"wesad_wrist_binary_{model_name}_rest5"
        write(HERE / "cross_train" / f"{train_name}.toml", train_name,
              f"Training side of the cross-dataset runs: WESAD wrist, {model_name}, binary.",
              "binary", model, norm="rest5", channels=WRIST, out_dir=f"runs/m5/cross_train/{train_name}")
        for exclude_hv in (False, True):
            hv = "nohv" if exclude_hv else "hv"
            test_name = f"sp_test_{hv}"
            if model_name == "bigru_attn":  # test-side data config, one per hyperventilation setting
                write(HERE / "cross_train" / f"{test_name}.toml", test_name,
                      "Test side of the cross-dataset runs: Stress-Predict wrist data (training settings unused).",
                      "binary", model, norm="rest5", dataset="stress_predict", channels=WRIST,
                      exclude_hv=exclude_hv, out_dir=f"runs/m5/cross_train/{test_name}")
            name = f"i_binary_{model_name}_wesad_to_sp_{hv}"
            (HERE / f"{name}.toml").write_text("\n".join([
                f"# Cross-dataset: {model_name} trained on WESAD wrist data, tested on Stress-Predict "
                f"(hyperventilation {'excluded' if exclude_hv else 'as stress'}).",
                "# Generated by make_configs.py; edit that script, not this file.",
                "", "[cross]", f'name = "{name}"',
                f'train_config = "configs/m5/cross_train/{train_name}.toml"',
                f'test_config = "configs/m5/cross_train/{test_name}.toml"',
                f'out_dir = "runs/m5/{name}"', "",
            ]), encoding="utf-8", newline="\n")

    counts = {g: len(list(HERE.glob(f"{g}_*.toml"))) for g in "eghi"}
    print(f"Wrote configs: {counts}")


if __name__ == "__main__":
    main()
