"""Write the M3 experiment configs into this folder.

    python Code/configs/m3/make_configs.py

Groups (file-name prefix):
  a_  design check: the BiGRU model with and without the downsampling front-end,
      10 s windows, four-class.
  b_  main comparison: six models x three tasks, 60 s windows.
  c_  window length: the proposed model at 10 and 30 s (60 s is in b_).
  d_  ablations of the proposed model: attention, depth, width, signals.

Every config shares one data pipeline and one training recipe, so the runs
differ only in what their names say. Run each group over several seeds with
``run_pipeline.py run --seeds 42 43 44 45 46``.
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent

CHEST = ["ch_ecg", "ch_eda", "ch_emg", "ch_resp", "ch_temp", "ch_acc_x", "ch_acc_y", "ch_acc_z"]
WRIST = ["wr_bvp", "wr_eda", "wr_temp", "wr_acc_x", "wr_acc_y", "wr_acc_z"]

# Front-end that shortens the sequence 16x before the recurrent layer.
DS16 = {"conv_channels": [64, 64, 64, 64], "downsample": [2, 2, 2, 2], "kernel_size": 5}

MODELS = {
    # 1. proposed: CNN front-end -> BiGRU -> attention
    "bigru_attn": {**DS16, "rnn": "gru", "bidirectional": True, "attention": True},
    # 2. the same with LSTM, to test the "GRU is lighter and as good" claim
    "bilstm_attn": {**DS16, "rnn": "lstm", "bidirectional": True, "attention": True},
    # 3. conventional CNN-LSTM: one direction, no attention
    "cnn_lstm": {**DS16, "rnn": "lstm", "bidirectional": False, "attention": False},
    # 4. convolutions only
    "cnn": {**DS16, "rnn": "none", "attention": False},
    # 5. BiGRU without the CNN (input average-pooled 16x so the length matches)
    "bigru_only": {"conv_channels": [], "downsample": [16], "rnn": "gru", "bidirectional": True, "attention": True},
    # 6. small depthwise-separable CNN, the candidate for on-device use
    "tiny_dscnn": {"conv_channels": [16, 32, 32, 32], "downsample": [2, 2, 2, 2], "kernel_size": 7,
                   "separable": True, "rnn": "none", "attention": False},
}

TASKS = ("binary", "three_class", "four_class")
STRIDE = {10: 5, 30: 5, 60: 10}  # 60 s windows at 10 s stride keep memory reasonable


def toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, list):
        return "[" + ", ".join(toml_value(x) for x in v) + "]"
    return str(v)


def write(name: str, comment: str, window: int, task: str, model: dict, channels: list[str] | None = None,
          channel_tag: str = "") -> None:
    data_dir = f"data_clean_w{window}_s{STRIDE[window]}_r32{channel_tag}"
    if window == 10 and not channel_tag:
        data_dir = "data_clean_w10_r32"  # same settings as clean_w10_weighted_sampler.toml
    model = {"rnn_hidden": 128, "rnn_layers": 2, "attn_heads": 4, "dropout": 0.3, **model}
    lines = [
        f"# {comment}",
        "# Generated by make_configs.py; edit that script, not this file.",
        "",
        "[run]",
        f'name = "{name}"',
        "seed = 42",
        "",
        "[paths]  # relative to Code/",
        'raw_dir = "WESAD"',
        f'data_dir = "{data_dir}"',
        f'out_dir = "runs/m3/{name}"',
        "",
        "[preprocess]",
        'mode = "clean"',
        "target_rate = 32",
        f"window_sec = {window}",
        f"stride_sec = {STRIDE[window]}",
        "min_label_purity = 1.0",
        "subject_normalisation = true",
    ]
    if channels:
        lines.append(f"channels = {toml_value(channels)}")
    lines += ["", "[model]", 'arch = "seq"']
    lines += [f"{k} = {toml_value(v)}" for k, v in model.items()]
    lines += [
        "",
        "[train]",
        f'task = "{task}"',
        'balancing = "weighted_sampler"',
        "batch_size = 128",
        "epochs = 40",
        "lr = 1e-3",
        'lr_scheduler = "plateau"',
        "patience = 8",
        "grad_clip = 5.0",
        'validation = "subjects"  # early stopping on two held-out training subjects',
        "val_subjects = 2",
        "val_fraction = 0.1       # unused with subject validation",
        "",
    ]
    (HERE / f"{name}.toml").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    for old in HERE.glob("*.toml"):
        old.unlink()

    no_ds = {**MODELS["bigru_attn"], "conv_channels": [64, 64], "downsample": [1, 1]}
    write("a_four_class_bigru_attn_nods_w10", "Design check: BiGRU + attention without downsampling (320 steps).",
          10, "four_class", no_ds)
    write("a_four_class_bigru_attn_w10", "Design check: BiGRU + attention with 16x downsampling (20 steps).",
          10, "four_class", MODELS["bigru_attn"])

    for task in TASKS:
        for model_name, model in MODELS.items():
            write(f"b_{task}_{model_name}_w60", f"Main comparison: {model_name}, {task}, 60 s windows.",
                  60, task, model)

    for task in TASKS:
        for window in (10, 30):
            write(f"c_{task}_bigru_attn_w{window}", f"Window length: bigru_attn, {task}, {window} s windows.",
                  window, task, MODELS["bigru_attn"])

    base = MODELS["bigru_attn"]
    ablations = {
        "no_attention": ({**base, "attention": False}, None, ""),
        "one_layer": ({**base, "rnn_layers": 1}, None, ""),
        "hidden32": ({**base, "rnn_hidden": 32}, None, ""),
        "hidden64": ({**base, "rnn_hidden": 64}, None, ""),
        "chest_only": (base, CHEST, "_chest"),
        "wrist_only": (base, WRIST, "_wrist"),
    }
    for tag, (model, channels, channel_tag) in ablations.items():
        write(f"d_four_class_bigru_attn_{tag}_w60", f"Ablation of bigru_attn: {tag}, four-class, 60 s windows.",
              60, "four_class", model, channels, channel_tag)

    print(f"Wrote {len(list(HERE.glob('*.toml')))} configs to {HERE}")


if __name__ == "__main__":
    main()
